services:
  web:
    build:
      context: ./backend
      dockerfile: Docker/Dockerfile
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

volumes:
  db_data: