version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql   

  backend:
    build: .
    container_name: backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:   # MySQLのデータ保存