# Generated by Django 5.2.14 on 2026-05-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/templates/', verbose_name='画像')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_templates', to='foods.prefood', verbose_name='カテゴリ')),
            ],
        ),
    ]
