# Generated by Django 5.2.14 on 2026-05-12 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='カテゴリー手入力'),
        ),
        migrations.AddField(
            model_name='food',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='賞味期限'),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/entry/', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='food',
            name='no_expiration_date',
            field=models.BooleanField(default=True, verbose_name='期限なし'),
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.prefood', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='食品'),
        ),
        migrations.AlterField(
            model_name='prefood',
            name='name',
            field=models.CharField(max_length=100, verbose_name='カテゴリー名'),
        ),
    ]
